import { defineConfig, type Plugin } from 'vitest/config'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { fileURLToPath, URL } from 'node:url'
import { readdirSync } from 'node:fs'

/**
 * A service worker that makes the built app work without a connection.
 *
 * Everything this app does is already local — the hands are in IndexedDB, the
 * coach runs in a worker in the tab, nothing is fetched from anywhere — so the
 * only thing standing between it and working on a train is the files
 * themselves. They are content-hashed, which makes them safe to keep forever
 * and simple to reason about: an asset either matches its name or it is a
 * different asset.
 *
 * Generated here rather than hand-written so the list of files to keep is the
 * list the build actually emitted, and never drifts from it.
 */
function offline(): Plugin {
  return {
    name: 'stat-poker-offline',
    apply: 'build',
    generateBundle(_options, bundle) {
      const built = Object.keys(bundle).map((file) => `./${file}`)
      // Anything in public/ is copied rather than bundled, so it is not in the
      // bundle to be read out of — it is read off disk for the same reason.
      const copied = readdirSync('public').map((file) => `./${file}`)
      const precache = ['./', './index.html', ...built, ...copied]
      // The cache is named for what is in it, so a deploy that changes any
      // file lands in a new cache and the old one is thrown away.
      const version = built.join('|').length.toString(36) + '-' + built.length

      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: serviceWorker(precache, version),
      })
    },
  }
}

function serviceWorker(precache: string[], version: string): string {
  return `/* Generated by vite.config.ts. Do not edit. */
const CACHE = 'stat-poker-${version}'
const PRECACHE = ${JSON.stringify(precache, null, 2)}

// Match on the address alone. A server that sends \`Vary: Origin\` — which is
// what a static host does the moment a file is asked for with crossorigin, and
// the module scripts are — makes a cached response match only a request whose
// headers agree, so the entry is there and never found. Every file here is
// content-hashed: its address is its identity, and nothing else about the
// request can change what it should be.
const MATCH = { ignoreVary: true }

self.addEventListener('install', (event) => {
  // Take over as soon as the new files are in: the alternative is a player
  // running last week's app until every tab is closed.
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(PRECACHE))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) => Promise.all(names.filter((n) => n !== CACHE).map((n) => caches.delete(n))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return

  // The page itself comes from the network when there is one, so a deploy is
  // picked up on the next load rather than whenever the cache happens to be
  // thrown away. Everything else is content-hashed and cannot go stale.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone()
          caches.open(CACHE).then((cache) => cache.put(request, copy))
          return response
        })
        .catch(() =>
          caches
            .match(request, MATCH)
            .then((hit) => hit ?? caches.match('./index.html', MATCH)),
        ),
    )
    return
  }

  event.respondWith(
    caches.match(request, MATCH).then(
      (hit) =>
        hit ??
        fetch(request).then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put(request, copy))
          }
          return response
        }),
    ),
  )
})
`
}

export default defineConfig({
  // Relative asset paths, so the built app runs from wherever it is served:
  // the root in development, and a repository subpath on GitHub Pages.
  base: './',
  plugins: [react(), tailwindcss(), offline()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url)),
    },
  },
  test: {
    include: ['src/**/*.test.ts'],
    // Exhaustive and simulation-based tests run for minutes by design.
    testTimeout: 300_000,
    hookTimeout: 300_000,
    teardownTimeout: 60_000,
  },
})
