/**
 * Regenerate `src/equity/preflop-table.ts`.
 *
 * The all-in equity of each of the 169 starting hands against a random hand is
 * a fixed property of the game, so it is computed once here and committed
 * rather than sampled on every app start. Run with:
 *
 *     npx vite-node scripts/generate-preflop-table.ts
 */

import { writeFileSync } from 'node:fs'
import { makeCard, NUM_RANKS, Rng, type Card } from '../src/engine/cards'
import { handEquity } from '../src/equity/equity'
import { comboClass, parseRange } from '../src/equity/range'

const ITERATIONS = 400_000

function representative(high: number, low: number, suited: boolean): [Card, Card] {
  if (high === low) return [makeCard(high, 0), makeCard(low, 1)]
  return suited ? [makeCard(high, 0), makeCard(low, 0)] : [makeCard(high, 0), makeCard(low, 1)]
}

const random = parseRange('random')
const rng = new Rng(0xc0ffee)
const rows: [string, number][] = []

for (let high = NUM_RANKS - 1; high >= 0; high--) {
  for (let low = high; low >= 0; low--) {
    for (const suited of high === low ? [false] : [true, false]) {
      const cards = representative(high, low, suited)
      const { equity } = handEquity(cards, [random], [], { rng, iterations: ITERATIONS })
      rows.push([comboClass(cards), Number(equity.toFixed(5))])
      process.stdout.write('.')
    }
  }
}

rows.sort((a, b) => b[1] - a[1])

const body = rows.map(([hand, equity]) => `  ['${hand}', ${equity}],`).join('\n')
const file = `/**
 * All-in equity of each starting hand against one random hand, best first.
 *
 * Generated by \`scripts/generate-preflop-table.ts\` with ${ITERATIONS.toLocaleString('en-US')}
 * rollouts per hand. Do not edit by hand — rerun the script.
 */

export const PREFLOP_EQUITY: readonly (readonly [string, number])[] = [
${body}
]
`

writeFileSync(new URL('../src/equity/preflop-table.ts', import.meta.url), file)
console.log(`\nWrote ${rows.length} hands.`)
