/**
 * Regenerate `src/solver/matchup-table.ts`.
 *
 * All-in equity of every starting-hand class against every other, sampled with
 * card removal respected — the pairs that share cards (aces against aces) get
 * fewer valid combinations, and that shows up in the numbers.
 *
 *     npx vite-node scripts/generate-matchup-table.ts
 */

import { writeFileSync } from 'node:fs'
import { NUM_CARDS, Rng, type Card } from '../src/engine/cards'
import { evaluate } from '../src/engine/evaluator'
import { comboClass, parseRange } from '../src/equity/range'
import { preflopRanking } from '../src/equity/preflop'

const ITERATIONS = 3_000

/** All 169 classes in a fixed order, with their combinations. */
const classes = preflopRanking().map((row) => row.hand)
const combosByClass = new Map<string, [Card, Card][]>()
for (const combo of parseRange('random')) {
  const key = comboClass(combo.cards)
  const list = combosByClass.get(key)
  const pair: [Card, Card] = [combo.cards[0], combo.cards[1]]
  if (list) list.push(pair)
  else combosByClass.set(key, [pair])
}

const rng = new Rng(0xd0d0)
const board: Card[] = new Array(5)
const heroHand: Card[] = new Array(7)
const villainHand: Card[] = new Array(7)
const deck: Card[] = new Array(NUM_CARDS)

/** Equity of `a` against `b`, sampling combinations of each that can coexist. */
function matchup(a: string, b: string): number {
  const aCombos = combosByClass.get(a)!
  const bCombos = combosByClass.get(b)!
  let total = 0
  let trials = 0

  for (let i = 0; i < ITERATIONS; i++) {
    const hero = aCombos[rng.nextInt(aCombos.length)]!
    const villain = bCombos[rng.nextInt(bCombos.length)]!
    if (
      hero[0] === villain[0] ||
      hero[0] === villain[1] ||
      hero[1] === villain[0] ||
      hero[1] === villain[1]
    ) {
      continue // the two classes cannot both hold these cards
    }

    let size = 0
    for (let card = 0; card < NUM_CARDS; card++) {
      if (card !== hero[0] && card !== hero[1] && card !== villain[0] && card !== villain[1]) {
        deck[size++] = card
      }
    }
    for (let k = 0; k < 5; k++) {
      const j = k + rng.nextInt(size - k)
      const tmp = deck[k]!
      deck[k] = deck[j]!
      deck[j] = tmp
      board[k] = deck[k]!
    }

    heroHand[0] = hero[0]
    heroHand[1] = hero[1]
    villainHand[0] = villain[0]
    villainHand[1] = villain[1]
    for (let k = 0; k < 5; k++) {
      heroHand[k + 2] = board[k]!
      villainHand[k + 2] = board[k]!
    }

    const mine = evaluate(heroHand)
    const theirs = evaluate(villainHand)
    total += mine > theirs ? 1 : mine === theirs ? 0.5 : 0
    trials++
  }

  return trials === 0 ? 0.5 : total / trials
}

const size = classes.length
const table = new Float64Array(size * size)
for (let i = 0; i < size; i++) {
  // A class against itself is a coin flip by symmetry — an exact fact, not
  // something to sample and get slightly wrong.
  table[i * size + i] = 0.5
  for (let j = i + 1; j < size; j++) {
    const equity = matchup(classes[i]!, classes[j]!)
    table[i * size + j] = equity
    // The mirror is exactly complementary, so only half needs sampling.
    table[j * size + i] = 1 - equity
  }
  process.stdout.write('.')
}

const rows: string[] = []
for (let i = 0; i < size; i++) {
  const row: number[] = []
  for (let j = 0; j < size; j++) row.push(Number(table[i * size + j]!.toFixed(4)))
  rows.push(`  [${row.join(',')}],`)
}

const file = `/**
 * All-in equity of each starting-hand class against each other, best hand
 * first, matching the order of \`CLASSES\`.
 *
 * Generated by \`scripts/generate-matchup-table.ts\` with ${ITERATIONS.toLocaleString('en-US')} samples
 * per pair. Do not edit by hand — rerun the script.
 */

export const CLASSES: readonly string[] = ${JSON.stringify(classes)}

export const CLASS_INDEX: Readonly<Record<string, number>> = Object.fromEntries(
  CLASSES.map((hand, index) => [hand, index]),
)

export const MATCHUP: readonly (readonly number[])[] = [
${rows.join('\n')}
]
`

writeFileSync(new URL('../src/solver/matchup-table.ts', import.meta.url), file)
console.log(`\nWrote ${size}x${size} matchups.`)
