/**
 * Regenerate `src/solver/blueprint-table.ts`.
 *
 * Solves heads-up preflop by vector CFR — every hand updated at every node in
 * one traversal — and ships the average strategy along with the exploitability
 * it converged to, so the app can state how solved its advice actually is.
 *
 * Why heads-up rather than six-handed: a strategy stored per hand per spot
 * needs the solver to visit each of them, and sampling deals across a
 * six-handed tree leaves almost every spot with a handful of observations.
 * Two million sampled iterations produced a "solution" that opened 2% under
 * the gun and did not raise aces. Solving the public tree with all 169 hands
 * at once removes the sampling entirely, and heads-up is the case where the
 * terminal values reduce to a matchup matrix.
 *
 * This is not a lesser target. Every hand folded to the small blind is a
 * heads-up preflop game at exactly these stakes.
 *
 * It solves one game per stack depth on the ladder. Depth changes the game
 * rather than shading it — twenty blinds is a shove-or-fold game and a hundred
 * is not — so a strategy is only ever read at a depth close to the one it was
 * solved for, and the ladder is what keeps "close" from having to mean "near
 * enough".
 *
 *     ITERATIONS=20000 npx vite-node scripts/generate-blueprint.ts
 */

import { writeFileSync } from 'node:fs'
import { CLASSES } from '../src/solver/matchup-table'
import { DEFAULT_CONFIG } from '../src/solver/preflop'
import { HeadsUpPreflopSolver, HAND_COUNT, type PublicNode } from '../src/solver/preflop-hu'

const ITERATIONS = Number(process.env.ITERATIONS ?? 20_000)

/**
 * Stack depths solved, in big blinds.
 *
 * Spaced so that every depth between thirty and two hundred blinds is within a
 * quarter of a rung, which is as far as a strategy may be stretched before it
 * is answering a different question.
 */
const DEPTHS = [40, 70, DEFAULT_CONFIG.stack, 150]

const started = Date.now()
const tables: string[] = []
const exploitabilities: string[] = []
let total = 0

for (const stack of DEPTHS) {
  const config = { players: 2, stack, smallBlind: DEFAULT_CONFIG.smallBlind }
  const solver = new HeadsUpPreflopSolver(config)
  console.log(`\n${stack} big blinds:`)
  solver.train(ITERATIONS, (done) => {
    if (done % 5_000 !== 0) return
    const elapsed = (Date.now() - started) / 1000
    console.log(`  ${done.toLocaleString('en-US')} / ${ITERATIONS.toLocaleString('en-US')} — ${elapsed.toFixed(0)}s`)
  })

  const exploitability = solver.exploitability()
  console.log(`  exploitability: ${exploitability.toFixed(6)} bb/hand`)
  exploitabilities.push(`  ${stack}: ${exploitability.toFixed(6)},`)

  /** Each decision node keyed by the seat and betting context that identify it. */
  const rows: string[] = []
  for (const node of solver.nodes() as PublicNode[]) {
    for (let hand = 0; hand < HAND_COUNT; hand++) {
      const strategy = solver.strategyFor(node, hand).map((p) => Number(p.toFixed(4)))
      // A hand that never plays this action anywhere adds nothing but bytes.
      if (strategy.every((p) => p === 0)) continue
      const key = `${node.toAct}|${CLASSES[hand]}|${node.context}|${node.actions.join('')}`
      rows.push(`    ${JSON.stringify(key)}: [${strategy.join(',')}],`)
    }
  }
  total += rows.length
  tables.push(`  ${stack}: {\n${rows.join('\n')}\n  },`)
}

const file = `/**
 * Solved heads-up preflop strategy, one game per stack depth.
 *
 * Generated by \`scripts/generate-blueprint.ts\` with
 * ${ITERATIONS.toLocaleString('en-US')} iterations of vector CFR per depth. Being two-player
 * and zero-sum, the exploitability below means what it says: no
 * counter-strategy can beat these by more than that many big blinds a hand.
 *
 * Depth changes the game rather than shading it, so each is solved rather than
 * borrowed from its neighbour.
 *
 * Keys are \`seat|hand|context|actions\`, where seat 0 is the small blind —
 * heads-up, the button — and the action digits are fold(0), call(1),
 * raise(2), all-in(3). Values are the frequency of each, in the same order.
 *
 * Limping is not modelled; the opening decision is raise or fold. A pot that
 * sees a flop is priced by all-in equity adjusted for the position it will be
 * played from; a pot that is already all-in is priced by the equity itself,
 * because it has no later streets for position to act on. Do not edit by hand
 * — rerun the script.
 */

export const BLUEPRINT_ITERATIONS = ${ITERATIONS}

/** Stack depths solved, in big blinds. */
export const BLUEPRINT_DEPTHS = [${DEPTHS.join(', ')}] as const

/** How far from equilibrium each depth's solve got, in big blinds per hand. */
export const BLUEPRINT_EXPLOITABILITY: Readonly<Record<number, number>> = {
${exploitabilities.join('\n')}
}

export const BLUEPRINTS: Readonly<Record<number, Readonly<Record<string, readonly number[]>>>> = {
${tables.join('\n')}
}
`

writeFileSync(new URL('../src/solver/blueprint-table.ts', import.meta.url), file)
console.log(`\nWrote ${total.toLocaleString('en-US')} entries across ${DEPTHS.length} depths in ${((Date.now() - started) / 1000).toFixed(0)}s.`)
